routes/web.php
<?php

// /*
// |--------------------------------------------------------------------------
// | Web Routes
// |--------------------------------------------------------------------------
// |
// | Here is where you can register web routes for your application. These
// | routes are loaded by the RouteServiceProvider within a group which
// | contains the "web" middleware group. Now create something great!
// |
// */


//frontend
Route::get('/','FrontEndController@home')->name('home');

// Route::get('/contact-us','FrontEndController@contact')->name('contact');

Route::get('/about-us/board-of-directors','FrontEndController@bod')->name('team');


Route::get('/about-us/bod','FrontEndController@bod')->name('team');

Route::get('/about-us/corporate-management','FrontEndController@corporate_management')->name('corporate');

Route::get('/about-us/board-of-directors','FrontEndController@bod')->name('team');


Route::get('/document','FrontEndController@download')->name('document');
//news and event
Route::get('/news/{slug}','FrontEndController@news')->name('news');
Route::get('/news-event','FrontEndController@newsmenu')->name('event');







Route::get('/branches','FrontEndController@branch')->name('branch');

Route::group(['as'=>'download.', 'prefix'=>'download'], function(){
Route::get('/proposal-forms','FrontEndController@propose')->name('proposal');
Route::get('/financial-reports','FrontEndController@finance')->name('finance');
Route::get('/kyc-form','FrontEndController@kyc')->name('kyc');
Route::get('/claim-intimation-form','FrontEndController@claim')->name('claim');
});

Route::get('insurance/{slug}','FrontEndController@insurances')->name('insurance');

Route::get('/about-us/company-profile-nepal','FrontEndController@about')->name('about');
Route::get('/about-us/company-profile-world','FrontEndController@company_profile_world')->name('world');
Route::get('/about-us/key-person','FrontEndController@key')->name('key');
Route::get('/profile-details/{slug}','FrontEndController@profile')->name('profile');

Route::get('contact', 'FrontEndController@getContact');
Route::post('contact','FrontEndController@postContact');

//login
Auth::routes();

Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::get('logout', 'Auth\LoginController@logout');

//backend
Route::get('/home', 'HomeController@dashboard')->name('dashboard');

Route::group([ 'prefix' => 'backend', 'middleware' => 'auth' ], function () {

//slider
Route::group(['as'=>'slider.', 'prefix'=>'slider' ], function(){
Route::get('','SliderController@index')->name('index');
Route::get('create','SliderController@create')->name('create');
Route::post('','SliderController@store')->name('store');
Route::put('{slider}','SliderController@update')->name('update');
Route::get('{slider}/edit','SliderController@edit')->name('edit');
Route::delete('{slider}','SliderController@delete')->name('destroy');
});


//news
Route::group(['as'=>'news.', 'prefix'=>'news' ], function(){
Route::get('','NewsController@index')->name('index');
Route::get('create','NewsController@create')->name('create');
Route::post('','NewsController@store')->name('store');
Route::put('{new}','NewsController@update')->name('update');
Route::get('{new}/edit','NewsController@edit')->name('edit');
Route::delete('{new}','NewsController@delete')->name('destroy');
});

//team
Route::group(['as'=>'team.', 'prefix'=>'team' ], function(){
Route::get('','TeamController@index')->name('index');
Route::get('create','TeamController@create')->name('create');
Route::post('','TeamController@store')->name('store');
Route::put('{team}','TeamController@update')->name('update');
Route::get('{team}/edit','TeamController@edit')->name('edit');
Route::delete('{team}','TeamController@delete')->name('destroy');
});

//download file
    Route::group([ 'as' => 'download.', 'prefix' => 'download' ], function ()
    {
        Route::get('', 'DownloadController@index')->name('index');
        Route::get('create', 'DownloadController@create')->name('create');
        Route::post('store', 'DownloadController@store')->name('store');
        Route::put('{download}', 'DownloadController@update')->name('update');
        Route::get('{download}/edit', 'DownloadController@edit')->name('edit');
        Route::delete('{download}', 'DownloadController@destroy')->name('destroy');

    });

    //image
      Route::group([ 'as' => 'photo.', 'prefix' => 'photo' ], function ()
        {
            Route::get('', 'PhotoController@index')->name('index');
            Route::get('create', 'PhotoController@create')->name('create');
            Route::post('store', 'PhotoController@store')->name('store');
            Route::put('{photo}', 'PhotoController@update')->name('update');
            Route::get('{photo}/edit', 'PhotoController@edit')->name('edit');
            Route::delete('{photo}', 'PhotoController@delete')->name('destroy');

        });

        //pages
          Route::group([ 'as' => 'page.', 'prefix' => 'page' ], function ()
            {
                Route::get('', 'PageController@index')->name('index');
                Route::get('create', 'PageController@create')->name('create');
                Route::post('store', 'PageController@store')->name('store');
                Route::put('{page}', 'PageController@update')->name('update');
                Route::get('{page}/edit', 'PageController@edit')->name('edit');
                Route::delete('{page}', 'PageController@delete')->name('destroy');

            });

            Route::group([ 'as' => 'insurance.', 'prefix' => 'insurance' ], function ()
              {
                  Route::get('', 'InsuranceController@index')->name('index');
                  Route::get('create', 'InsuranceController@create')->name('create');
                  Route::post('store', 'InsuranceController@store')->name('store');
                  Route::put('{insurance}', 'InsuranceController@update')->name('update');
                  Route::get('{insurance}/edit', 'InsuranceController@edit')->name('edit');
                  Route::delete('{insurance}', 'InsuranceController@delete')->name('destroy');

              });
});

app/Insurance.php
<?php

namespace App;

use Spatie\Sluggable\HasSlug;
use Spatie\Sluggable\SlugOptions;
use Illuminate\Database\Eloquent\Model;

class Insurance extends Model
{
  protected $fillable=[
    'title',
    'slug',
    'meta_description',
    'content',
    'is_published',

  ];

  protected $casts=[
    'is_published'=>'boolean'
  ];

  use HasSlug;

 /**
  * Get the options for generating the slug.
  */
 public function getSlugOptions() : SlugOptions
 {
     return SlugOptions::create()
         ->generateSlugsFrom('title')
         ->saveSlugsTo('slug');
 }
 /**
  * Get the route key for the model.
  *
  * @return string
  */
 public function getRouteKeyName()
 {
     return 'slug';
 }
 /**
  * @param $query
  * @param bool $type
  * @return mixed
  */
 public function scopePublished($query, $type = true)
 {
     return $query->where('is_published', $type);
 }

 /**
  * @param $query
  * @param bool $type
  * @return mixed
  */
 public function scopePrimary($query, $type = true)
 {
     return $query->where('is_primary', $type);
 }

 /**
  * @return \Illuminate\Database\Eloquent\Relations\MorphOne
  */
 public function image()
 {
     return $this->morphOne(Image::class, 'imageable');
 }

 /**
  * @param array $options
  * @return bool|null|void
  * @throws \Exception
  */
 public function delete(array $options = array())
 {
     if ($this->image)
     {
         $this->image->delete();
       }

     return parent::delete($options);
 }
}

app/Http/Controllers/InsuranceController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\StoreInsurance;
use App\Http\Requests\UpdateInsurance;
use Illuminate\Support\Facades\DB;
use App\Image;
use App\Insurance;

class InsuranceController extends Controller
{
  public function index()
  {
    $insurances = Insurance::latest()->get();
    return view('backend.insurance.index',compact('insurances'));
  }

  public function create()
  {
    return view('backend.insurance.create');
  }

  public function store(StoreInsurance $request)
  {
    DB::transaction( function () use ($request)
    {
      $data = $request->data();
      $insurance = Insurance::create($data);
      $this->uploadRequestImage($request,$insurance);
    });
    return redirect()->route('insurance.index')->withsuccess(trans('insurance pages has been successfully created',[ 'entity' => 'insurance']));
  }

  public function show(Insurance $insurance)
  {
    return view($insurance->view,compact('insurances'));
  }

  public function edit(Insurance $insurance)
  {
    return view('backend.insurance.edit',compact('insurance'));
  }

  public function update(UpdateInsurance $request,Insurance $insurance)
  {
    DB::transaction(function () use($request,$insurance)
    {
      $insurance->update($request->data());

      $this->uploadRequestImage($request,$insurance);
    });
    return redirect()->route('insurance.index')->withsuccess(trans('insurance pages has been successfully updated',['entity'=>'insurance']));
  }

  public function delete(insurance $insurance)
  {
       $insurance->delete();

        return back()->withsuccess(trans('insurance has been deleted successfully', ['entity'=>'insurance']));
  }

}

resources/views/backend/insurance/partials/form.blade.php
<div class="row">
  <div class="col-md-12">
    @include('partials.errors')
  </div>
  <div class="col-sm-8">
    <div class="card">
      <div class="card-head">
        <header><h4>{!! $header !!}</h4></header>
        <div class="tools visible-xs">
          <a class="btn btn-default btn-ink" onclick="history.go(-1);return false;">
            <i class="md md-arrow-back"></i>
            Back
          </a>
          <input type="submit" name="draft" class="btn btn-info ink-reaction" value="Save Draft">
          <input type="submit" name="publish" class="btn btn-primary ink-reaction" value="Publish">
        </div>
      </div>
      <div class="card-body">
        <div class="row">
          <div class="col-sm-12">
            <div class="form-group">

              <strong>Title</strong>
              {{ Form::text('title',old('title'),['class'=>'form-control','required']) }}

            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-12">
            <div class="form-group">
              <strong>Sub_description</Strong>
                <br>
                {{ Form::textarea('meta_description',old('meta_description'),['class'=>'form-control','rows'=>2 ,'cols'=>40]) }}

              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-sm-12">
              <div class="form-group">
                <strong>Content<Strong>
                  <br>
                  {{ Form::textarea('content',old('content'),['required', 'id' => 'my-ckeditor']) }}

                </div>
              </div>
            </div>

            <div class="row">
              <div class="col-sm-12">
                <label class="text-default-dark"><strong>Featured Image</strong></label>
                <br>
                <br>
                @if(isset($insurance) && $insurance->image)
                <input type="file" name="image" class="dropify" data-default-file="{{ asset($insurance->image->path) }}"/>
                @else
                <input type="file" name="image" class="dropify"/>
                @endif
              </div>
            </div>
          </div>
          <br>
          <br>
          <div class="card-actionbar">
            <div class="card-actionbar-row">
              <button type="reset" class="btn btn-default ink-reaction">Reset</button>
              <input type="submit" name="draft" class="btn btn-info ink-reaction" value="Save Draft">
              <input type="submit" name="publish" class="btn btn-primary ink-reaction" value="{{ isset($insurance) && $insurance->is_published ? 'Save' : 'Publish' }}">
            </div>
          </div>
        </div>
      </div>
    </div>

    @push('scripts')
    <script src="{{asset('vendor/unisharp/laravel-ckeditor/ckeditor.js')}}"></script>
    <script src="{{asset('vendor/unisharp/laravel-ckeditor/adapters/jquery.js')}}"></script>
    <script>
    CKEDITOR.replace( 'my-ckeditor' );
    </script>
    @endpush

resources/views/backend/insurance/partials/table.blade.php
<tr>
    <td>{{++$key}}</td>
    <td>{{ str_limit($insurance->title,15) }}</td>
    <td>{!!str_limit($insurance->content,35) !!}</td>
    <td class="text-center">
        <span class="badge">{{ $insurance->is_published ? 'Yes' : 'No' }}</span>
</td>

<td class="text-right">
 <a href="{{route('insurance.edit', $insurance->slug)}}" class="btn btn-flat btn-primary btn-xs">
     Edit
 </a>
 <button type="button" data-url="{{ route('insurance.destroy', $insurance->slug) }}"
         class="btn btn-flat btn-primary btn-xs item-delete">
     Delete
 </button>
</td>
</tr>