routes/web.php
<?php

// /*
// |--------------------------------------------------------------------------
// | Web Routes
// |--------------------------------------------------------------------------
// |
// | Here is where you can register web routes for your application. These
// | routes are loaded by the RouteServiceProvider within a group which
// | contains the "web" middleware group. Now create something great!
// |
// */


//frontend
Route::get('/','FrontEndController@home')->name('home');

// Route::get('/contact-us','FrontEndController@contact')->name('contact');

Route::get('/about-us/board-of-directors','FrontEndController@bod')->name('team');


Route::get('/about-us/bod','FrontEndController@bod')->name('team');

Route::get('/about-us/corporate-management','FrontEndController@corporate_management')->name('corporate');

Route::get('/about-us/board-of-directors','FrontEndController@bod')->name('team');


Route::get('/document','FrontEndController@download')->name('document');
//news and event
Route::get('/news/{slug}','FrontEndController@news')->name('news');
Route::get('/news-event','FrontEndController@newsmenu')->name('event');







Route::get('/branches','FrontEndController@branch')->name('branch');

Route::group(['as'=>'download.', 'prefix'=>'download'], function(){
Route::get('/proposal-forms','FrontEndController@propose')->name('proposal');
Route::get('/financial-reports','FrontEndController@finance')->name('finance');
Route::get('/kyc-form','FrontEndController@kyc')->name('kyc');
Route::get('/claim-intimation-form','FrontEndController@claim')->name('claim');
});

Route::get('insurance/{slug}','FrontEndController@insurances')->name('insurance');

Route::get('/about-us/company-profile-nepal','FrontEndController@about')->name('about');
Route::get('/about-us/company-profile-world','FrontEndController@company_profile_world')->name('world');
Route::get('/about-us/key-person','FrontEndController@key')->name('key');
Route::get('/profile-details/{slug}','FrontEndController@profile')->name('profile');

Route::get('contact', 'FrontEndController@getContact');
Route::post('contact','FrontEndController@postContact');

//login
Auth::routes();

Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::get('logout', 'Auth\LoginController@logout');

//backend
Route::get('/home', 'HomeController@dashboard')->name('dashboard');

Route::group([ 'prefix' => 'backend', 'middleware' => 'auth' ], function () {

//slider
Route::group(['as'=>'slider.', 'prefix'=>'slider' ], function(){
Route::get('','SliderController@index')->name('index');
Route::get('create','SliderController@create')->name('create');
Route::post('','SliderController@store')->name('store');
Route::put('{slider}','SliderController@update')->name('update');
Route::get('{slider}/edit','SliderController@edit')->name('edit');
Route::delete('{slider}','SliderController@delete')->name('destroy');
});


//news
Route::group(['as'=>'news.', 'prefix'=>'news' ], function(){
Route::get('','NewsController@index')->name('index');
Route::get('create','NewsController@create')->name('create');
Route::post('','NewsController@store')->name('store');
Route::put('{new}','NewsController@update')->name('update');
Route::get('{new}/edit','NewsController@edit')->name('edit');
Route::delete('{new}','NewsController@delete')->name('destroy');
});

//team
Route::group(['as'=>'team.', 'prefix'=>'team' ], function(){
Route::get('','TeamController@index')->name('index');
Route::get('create','TeamController@create')->name('create');
Route::post('','TeamController@store')->name('store');
Route::put('{team}','TeamController@update')->name('update');
Route::get('{team}/edit','TeamController@edit')->name('edit');
Route::delete('{team}','TeamController@delete')->name('destroy');
});

//download file
    Route::group([ 'as' => 'download.', 'prefix' => 'download' ], function ()
    {
        Route::get('', 'DownloadController@index')->name('index');
        Route::get('create', 'DownloadController@create')->name('create');
        Route::post('store', 'DownloadController@store')->name('store');
        Route::put('{download}', 'DownloadController@update')->name('update');
        Route::get('{download}/edit', 'DownloadController@edit')->name('edit');
        Route::delete('{download}', 'DownloadController@destroy')->name('destroy');

    });

    //image
      Route::group([ 'as' => 'photo.', 'prefix' => 'photo' ], function ()
        {
            Route::get('', 'PhotoController@index')->name('index');
            Route::get('create', 'PhotoController@create')->name('create');
            Route::post('store', 'PhotoController@store')->name('store');
            Route::put('{photo}', 'PhotoController@update')->name('update');
            Route::get('{photo}/edit', 'PhotoController@edit')->name('edit');
            Route::delete('{photo}', 'PhotoController@delete')->name('destroy');

        });

        //pages
          Route::group([ 'as' => 'page.', 'prefix' => 'page' ], function ()
            {
                Route::get('', 'PageController@index')->name('index');
                Route::get('create', 'PageController@create')->name('create');
                Route::post('store', 'PageController@store')->name('store');
                Route::put('{page}', 'PageController@update')->name('update');
                Route::get('{page}/edit', 'PageController@edit')->name('edit');
                Route::delete('{page}', 'PageController@delete')->name('destroy');

            });

            Route::group([ 'as' => 'insurance.', 'prefix' => 'insurance' ], function ()
              {
                  Route::get('', 'InsuranceController@index')->name('index');
                  Route::get('create', 'InsuranceController@create')->name('create');
                  Route::post('store', 'InsuranceController@store')->name('store');
                  Route::put('{insurance}', 'InsuranceController@update')->name('update');
                  Route::get('{insurance}/edit', 'InsuranceController@edit')->name('edit');
                  Route::delete('{insurance}', 'InsuranceController@delete')->name('destroy');

              });
});

resources/views/backend/page/create.blade.php
@extends('backend.layouts.app')

@section('title', 'page')

@section('content')
    <section>
        <div class="section-body">
            {{ Form::open(['route' =>'page.store','class'=>'form form-validate','role'=>'form', 'files'=>true, 'novalidate']) }}
            @include('backend.page.partials.form', ['header' => 'Create a pages'])
            {{ Form::close() }}
        </div>
    </section>
@stop


@push('styles')
<link href="{{ asset('backend/css/libs/dropify/dropify.min.css') }}" rel="stylesheet">
@endpush

@push('scripts')
<script src="{{ asset('backend/js/libs/jquery-validation/dist/jquery.validate.min.js') }}"></script>
<script src="{{ asset('backend/js/libs/jquery-validation/dist/additional-methods.min.js') }}"></script>
<script src="{{ asset('backend/js/libs/dropify/dropify.min.js') }}"></script>
@endpush

resources/views/backend/page/edit.blade.php
      @extends('backend.layouts.app')

@section('title', 'pages')

@section('content')
    <section>
        <div class="section-body">
            {{ Form::model($page, ['route' =>['page.update', $page->slug],'class'=>'form form-validate','role'=>'form', 'files'=>true, 'novalidate']) }}
            {{ method_field('PUT') }}
            @include('backend.page.partials.form', ['header' => 'Edit Page <span class="text-primary">('.str_limit($page->title, 47).')</span>'])
            {{ Form::close() }}
        </div>
    </section>
@stop

@push('styles')
<link href="{{ asset('backend/css/libs/dropify/dropify.min.css') }}" rel="stylesheet">
@endpush

@push('scripts')
<script src="{{ asset('backend/js/libs/jquery-validation/dist/jquery.validate.min.js') }}"></script>
<script src="{{ asset('backend/js/libs/jquery-validation/dist/additional-methods.min.js') }}"></script>
<script src="{{ asset('backend/js/libs/dropify/dropify.min.js') }}"></script>
@endpush

resources/views/backend/page/index.blade.php
@extends('backend.layouts.app')

@section('title', 'Pages')

@section('content')
    <section>
        <div class="section-body">
            <div class="card">
                <div class="card-head">
                    <header class="text-capitalize">all pages</header>
                    <div class="tools">
                        <a class="btn btn-primary ink-reaction" href="{{ route('page.create') }}">
                            <i class="md md-add"></i>
                            Add
                        </a>
                    </div>
                </div>
                <div class="card-body">
                    <table class="table table-hover">
                        <thead>
                        <tr>
                          <th width="10%">#</th>
                          <th width="40%">Title</th>
                          <th width="40%">Content</th>
                          <th width="30%" >Published</th>
                          <th width="10%" class="text-right">Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                          @if($pages->isEmpty())
                            <tr>
                                <td class="text-center" colspan="5">No data available.</td>
                            </tr>
                        @else
                        @each('backend.page.partials.table', $pages, 'page')
                        @endif

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>
@stop