routes/web.php
<?php

// /*
// |--------------------------------------------------------------------------
// | Web Routes
// |--------------------------------------------------------------------------
// |
// | Here is where you can register web routes for your application. These
// | routes are loaded by the RouteServiceProvider within a group which
// | contains the "web" middleware group. Now create something great!
// |
// */


//frontend
Route::get('/','FrontEndController@home')->name('home');

// Route::get('/contact-us','FrontEndController@contact')->name('contact');

Route::get('/about-us/board-of-directors','FrontEndController@bod')->name('team');


Route::get('/about-us/bod','FrontEndController@bod')->name('team');

Route::get('/about-us/corporate-management','FrontEndController@corporate_management')->name('corporate');

Route::get('/about-us/board-of-directors','FrontEndController@bod')->name('team');


Route::get('/document','FrontEndController@download')->name('document');
//news and event
Route::get('/news/{slug}','FrontEndController@news')->name('news');
Route::get('/news-event','FrontEndController@newsmenu')->name('event');







Route::get('/branches','FrontEndController@branch')->name('branch');

Route::group(['as'=>'download.', 'prefix'=>'download'], function(){
Route::get('/proposal-forms','FrontEndController@propose')->name('proposal');
Route::get('/financial-reports','FrontEndController@finance')->name('finance');
Route::get('/kyc-form','FrontEndController@kyc')->name('kyc');
Route::get('/claim-intimation-form','FrontEndController@claim')->name('claim');
});

Route::get('insurance/{slug}','FrontEndController@insurances')->name('insurance');

Route::get('/about-us/company-profile-nepal','FrontEndController@about')->name('about');
Route::get('/about-us/company-profile-world','FrontEndController@company_profile_world')->name('world');
Route::get('/about-us/key-person','FrontEndController@key')->name('key');
Route::get('/profile-details/{slug}','FrontEndController@profile')->name('profile');

Route::get('contact', 'FrontEndController@getContact');
Route::post('contact','FrontEndController@postContact');

//login
Auth::routes();

Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::get('logout', 'Auth\LoginController@logout');

//backend
Route::get('/home', 'HomeController@dashboard')->name('dashboard');

Route::group([ 'prefix' => 'backend', 'middleware' => 'auth' ], function () {

//slider
Route::group(['as'=>'slider.', 'prefix'=>'slider' ], function(){
Route::get('','SliderController@index')->name('index');
Route::get('create','SliderController@create')->name('create');
Route::post('','SliderController@store')->name('store');
Route::put('{slider}','SliderController@update')->name('update');
Route::get('{slider}/edit','SliderController@edit')->name('edit');
Route::delete('{slider}','SliderController@delete')->name('destroy');
});


//news
Route::group(['as'=>'news.', 'prefix'=>'news' ], function(){
Route::get('','NewsController@index')->name('index');
Route::get('create','NewsController@create')->name('create');
Route::post('','NewsController@store')->name('store');
Route::put('{new}','NewsController@update')->name('update');
Route::get('{new}/edit','NewsController@edit')->name('edit');
Route::delete('{new}','NewsController@delete')->name('destroy');
});

//team
Route::group(['as'=>'team.', 'prefix'=>'team' ], function(){
Route::get('','TeamController@index')->name('index');
Route::get('create','TeamController@create')->name('create');
Route::post('','TeamController@store')->name('store');
Route::put('{team}','TeamController@update')->name('update');
Route::get('{team}/edit','TeamController@edit')->name('edit');
Route::delete('{team}','TeamController@delete')->name('destroy');
});

//download file
    Route::group([ 'as' => 'download.', 'prefix' => 'download' ], function ()
    {
        Route::get('', 'DownloadController@index')->name('index');
        Route::get('create', 'DownloadController@create')->name('create');
        Route::post('store', 'DownloadController@store')->name('store');
        Route::put('{download}', 'DownloadController@update')->name('update');
        Route::get('{download}/edit', 'DownloadController@edit')->name('edit');
        Route::delete('{download}', 'DownloadController@destroy')->name('destroy');

    });

    //image
      Route::group([ 'as' => 'photo.', 'prefix' => 'photo' ], function ()
        {
            Route::get('', 'PhotoController@index')->name('index');
            Route::get('create', 'PhotoController@create')->name('create');
            Route::post('store', 'PhotoController@store')->name('store');
            Route::put('{photo}', 'PhotoController@update')->name('update');
            Route::get('{photo}/edit', 'PhotoController@edit')->name('edit');
            Route::delete('{photo}', 'PhotoController@delete')->name('destroy');

        });

        //pages
          Route::group([ 'as' => 'page.', 'prefix' => 'page' ], function ()
            {
                Route::get('', 'PageController@index')->name('index');
                Route::get('create', 'PageController@create')->name('create');
                Route::post('store', 'PageController@store')->name('store');
                Route::put('{page}', 'PageController@update')->name('update');
                Route::get('{page}/edit', 'PageController@edit')->name('edit');
                Route::delete('{page}', 'PageController@delete')->name('destroy');

            });

            Route::group([ 'as' => 'insurance.', 'prefix' => 'insurance' ], function ()
              {
                  Route::get('', 'InsuranceController@index')->name('index');
                  Route::get('create', 'InsuranceController@create')->name('create');
                  Route::post('store', 'InsuranceController@store')->name('store');
                  Route::put('{insurance}', 'InsuranceController@update')->name('update');
                  Route::get('{insurance}/edit', 'InsuranceController@edit')->name('edit');
                  Route::delete('{insurance}', 'InsuranceController@delete')->name('destroy');

              });
});

app/Download.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\Sluggable\HasSlug;
use Spatie\Sluggable\SlugOptions;

class Download extends Model
{
    protected $fillable = [

        'slug',
        'title',
        'path',
        'file_name',
        'size',
        'extension',
        'view',
        'is_published'
    ];

    protected $appends = [
        'public_path'
    ];


    /**
     * The attributes that should be typecast into boolean.
     *
     * @var array
     */
    public static $path = 'downloads/';


    protected $casts = [
        'is_published'    => 'boolean'
    ];


    /**
     * Get the route key for the model.
     *
     * @return string
     */
    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function getPublicPathAttribute()
    {
        $link = Download::$path . $this->path;
        return $link;
    }


        //for slug
        use HasSlug;

           /**
            * Get the options for generating the slug.
            */
           public function getSlugOptions() : SlugOptions
           {
               return SlugOptions::create()
                   ->generateSlugsFrom('title')
                   ->saveSlugsTo('slug');
           }




}

app/Http/Controllers/DownloadController.php
<?php

namespace App\Http\Controllers;

use App\Download;
use App\Http\Requests\StoreDownload;
use App\Http\Requests\UpdateDownload;
use Illuminate\Http\Request;

use App\Http\Requests;
use Illuminate\Support\Facades\DB;

class DownloadController extends Controller
{
    public function index()
    {
        $downloads = Download::orderBy('id', "ASC")->get();

        return view('backend.download.index', compact('downloads'));
    }


    public function create()
    {
        return view('backend.download.create');
    }

    public function store(StoreDownload $request)
    {
        DB::transaction(function () use ($request)
        {
            Download::create($request->data());
        });

        return redirect()->route('download.index')->withSuccess(' download file has been uploaded successfully');
    }

    public function edit(Download $download)
    {
        return view('backend.download.edit', compact('download'));
    }

    public function update(UpdateDownload $request, Download $download)
    {
        DB::transaction(function () use ($request, $download)
        {
            $download->update($request->data($download));
        });

        return redirect()->route('download.index')->withSuccess('download file has been  successfully updated');
    }

    public function destroy(Download $download)
    {
        {

            $download->delete();

            return back()->withSuccess('download file has been successfully deleted.');
        }
    }

}

app/Http/Controllers/FrontEndController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Slider;
use App\News;
use App\Team;
use App\Download;
use App\Photo;
use App\Page;
use App\Insurance;
use Mail;

class FrontEndController extends Controller
{
  public function home( $slug = null )
  {
    $news   = News::orderBy('created_at','desc')->take(3)->get();
    $slider = Slider::get()->all();
    $popup =  Photo::where('view','popup image')->orderBy('created_at','desc')->take(1)->get();
    $client = Photo::where('view','client')->get();
    $service = Insurance::get()->all();
    return view('index',compact('slider','news','popup','client','service'));
  }

  public function news($slug = null)
  {
    $new = News::whereSlug($slug)->first();
    $related_news = News::whereNotIn('id',[$new->id])->orderBy('created_at','desc')->take(5)->get();
    return view('frontend.news.index',compact('new','related_news'));
  }

  public function newsmenu()
  {
    $new = News::get()->all();
    return view('frontend.news.news-menu',compact('new'));
  }

  public function bod()
  {
    $team = Team::where('view','board-of-director')->get();
    return view('frontend.layouts.partials.bod',compact('team'));
  }
  public function corporate_management()
  {
    $corporate = Team::where('view','corporate-management')->get();
    return view('frontend.layouts.partials.corporate-management',compact('corporate'));
  }
  public function finance()
  {
    $financial_report = Download::where('view','financial reports')->get();

    return view('frontend.download.financial-report',compact('financial_report'));
  }

  public function claim()
  {
    $claim = Download::where('view','claim intimation form')->get();
    return view('frontend.download.claim-intimation',compact('claim'));
  }

  public function kyc()
  {
    $kyc = Download::where('view','kyc form')->get();
    return view('frontend.download.kyc',compact('kyc'));
  }

  public function propose()
  {
    $proposal_forms = Download::where('view','proposal forms')->get();
    return view('frontend.download.proposal-forms',compact('proposal_forms'));
  }

  public function branch()
  {
    return view('frontend.layouts.partials.branches');
  }


  public function insurances($slug = null)
  {
    $insurance = Insurance::whereSlug($slug)->first();
    $tender = Download::where('view','others')->get();

    return view('frontend.layouts.partials.insurance',compact('insurance','tender'));
  }




  public function about()
  {
    $company = Page::whereSlug('company-profile')->first();

    $mission = Page::whereSlug('mission')->first();
    $vision = Page::whereSlug('vision')->first();

    return view('frontend.layouts.partials.about-us',compact('company','mission','vision'));
  }

  public function company_profile_world()
  {
    $company_profile = Page::whereSlug('company-profile-world')->first();
    $vision = Page::whereSlug('vision')->first();
    $mission = Page::whereSlug('mission')->first();
    $products = Page::whereSlug('products-of-national-insurance')->first();
    $corporate = Page::whereSlug('corporate-social-responsibility')->first();
    $awards    = Page::whereSlug('awards-achievements')->first();
    return view('frontend.layouts.partials.company-profile-world',compact('vision','company_profile','mission','products','corporate','awards'));
  }
  public function key()
  {
    $key = Page::whereSlug('key-person')->first();
    return view('frontend.layouts.partials.key-person',compact('key'));
  }


  public function profile( $slug = null)
  {
    $bod = Team::whereSlug($slug)->first();
    return view('frontend.layouts.partials.profile-details',compact('bod'));
  }


  public function getContact()
  {

    return view('frontend.layouts.partials.contact');
  }
  public function PostContact(Request $request )
  {
    $this->validate($request,[
      'name'=>'required',
      'email'=>'required|email',
      'subject  '=>'required|max:200',
      'message'=>'required'

    ]);
    $data = array(
      'name'  =>$request->name,
      'email' => $request->email,
      'subject' => $request->subject,
      'bodyMessage' => $request->message
    )   ;


    Mail::send('emails.contact', $data,function($message) use($data){
      $message->from($data['email']);
      $message->to('badevilanish@gmail.com');
      $message->subject($data['subject']);



    });
  }
}

resources/views/frontend/download/claim-intimation.blade.php
@extends('frontend.layouts.app')

@section('title','claim-intimation-form')

@section('content')

<style>
.download h2{
background-color: #056608;
padding: 7px 20px;
color: #fff;
font-size: 20px;
}
.brochures ul>li:before{
    content: "\f0da";
    font-family: 'FontAwesome';
    margin: 0 2px;
    left: 0;
    position: absolute;
    color: #fe0000;
    font-weight: 700;

  }
</style>



	<section class="news-content section-padding single-service-page our-features in-wrapper no-container">
		<div class="container">
			<div class="row">
				<div class="col-md-4 download">
	        <h2><b>Quick Links</b></h2>
					<div class="single-sidebar-box service-link-widget">
						<ul class="catergori-list">
							<li><a href="{{route('download.finance')}}">Financial Reports</a></li>
							<li><a href="{{route('download.proposal')}}">Purposal Forms</a></li>
							<li class="active"><a href="{{route('download.claim')}}">Claim Intimation Form</a></li>
							<li><a href="{{route('download.kyc')}}">Kyc Form</a></li>




					</div>
				</div>
        	<!-- <h5 class="uppercase">Our Brochures</h5> -->

				<div class="col-md-8">
											    @foreach($claim as $data)
					<div class="single-sidebar-box service-link-widget">

						<div class="brochures">
							<!-- <br> -->
							<ul class="brochures-lists">
								<li class="active">
				<a href="{{URL::asset("/downloads/$data->path")}}" target="_blank">
										<span>{{$data->extension}}</span>{{$data->title}}<i class="fa fa-download"></i>
									</a>
								</li>
							</ul>
						</div>

					</div>
					@endforeach
				</div>



			</div>
		</div>
	</section>


@endsection

resources/views/frontend/download/financial-report.blade.php
@extends('frontend.layouts.app')

@section('title','financial-report')

@section('content')

<style>
.download h2{
background-color: #056608;
padding: 7px 20px;
color: #fff;
font-size: 20px;
}
.brochures ul>li:before{
    content: "\f0da";
    font-family: 'FontAwesome';
    margin: 0 2px;
    left: 0;
    position: absolute;
    color: #fe0000;
    font-weight: 700;

  }
</style>



	<section class="news-content section-padding single-service-page our-features in-wrapper no-container">
		<div class="container">
			<div class="row">
				<div class="col-md-4 download">
	        <h2><b>Quick Links</b></h2>
					<div class="single-sidebar-box service-link-widget">
						<ul class="catergori-list">
							<li class="active"><a href="{{route('download.finance')}}">Financial Reports</a></li>
							<li><a href="{{route('download.proposal')}}">Purposal Forms</a></li>
							<li><a href="{{route('download.claim')}}">Claim Intimation Form</a></li>
							<li><a href="{{route('download.kyc')}}">Kyc Form</a></li>




					</div>
				</div>
        	<!-- <h5 class="uppercase">Our Brochures</h5> -->

				<div class="col-md-8">
					 @foreach($financial_report as $data)
					<div class="single-sidebar-box service-link-widget">
										<!-- <br> -->
						<div class="brochures">
							<ul class="brochures-lists">
								<li class="active">
				<a href="{{URL::asset("/downloads/$data->path")}}" target="_blank">
										<span>{{$data->extension}}</span>{{$data->title}}<i class="fa fa-download"></i>
									</a>
								</li>
							</ul>

						</div>

					</div>
						@endforeach
				</div>



			</div>
		</div>
	</section>


@endsection

resources/views/frontend/download/kyc.blade.php
@extends('frontend.layouts.app')

@section('title','kyc-form')

@section('content')

<style>
.download h2{
background-color: #056608;
padding: 7px 20px;
color: #fff;
font-size: 20px;
}
.brochures ul>li:before{
    content: "\f0da";
    font-family: 'FontAwesome';
    margin: 0 2px;
    left: 0;
    position: absolute;
    color: #fe0000;
    font-weight: 700;

  }
</style>



	<section class="news-content section-padding single-service-page our-features in-wrapper no-container">
		<div class="container">
			<div class="row">
				<div class="col-md-4 download">
	        <h2><b>Quick Links</b></h2>
					<div class="single-sidebar-box service-link-widget">
						<ul class="catergori-list">
							<li><a href="{{route('download.finance')}}">Financial Reports</a></li>
							<li><a href="{{route('download.proposal')}}">Purposal Forms</a></li>
							<li><a href="{{route('download.claim')}}">Claim Intimation Form</a></li>
							<li class="active"><a href="{{route('download.kyc')}}">Kyc Form</a></li>



					</div>
				</div>
        	<!-- <h5 class="uppercase">Our Brochures</h5> -->

				<div class="col-md-8">
						  @foreach($kyc as $data)
					<div class="single-sidebar-box service-link-widget">

						<div class="brochures">
							<!-- <br> -->
							<ul class="brochures-lists">
								<li class="active">
				<a href="{{URL::asset("/downloads/$data->path")}}" target="_blank">
										<span>{{$data->extension}}</span>{{$data->title}}<i class="fa fa-download"></i>
									</a>
								</li>
							</ul>
						</div>

					</div>
							@endforeach
				</div>



			</div>
		</div>
	</section>


@endsection

resources/views/frontend/download/proposal-forms.blade.php
@extends('frontend.layouts.app')

@section('title','proposal-forms')

@section('content')

<style>
.download h2{
background-color: #056608;
padding: 7px 20px;
color: #fff;
font-size: 20px;
}
</style>



	<section class="news-content section-padding single-service-page our-features in-wrapper no-container">
		<div class="container">
			<div class="row">
				<div class="col-md-4 download">
	        <h2><b>Quick Links</b></h2>
					<div class="single-sidebar-box service-link-widget">
						<ul class="catergori-list">
							<li><a href="{{route('download.finance')}}">Financial Reports</a></li>
							<li class="active"><a href="{{route('download.proposal')}}">Purposal Forms</a></li>
							<li><a href="{{route('download.claim')}}">Claim Intimation Form</a></li>
							<li><a href="{{route('download.kyc')}}">Kyc Form</a></li>




					</div>
				</div>
        	<!-- <h5 class="uppercase">Our Brochures</h5> -->

				<div class="col-md-8">
					<div class="single-sidebar-box service-link-widget">
						  @foreach($proposal_forms as $data)
						<div class="brochures">
							<!-- <br> -->
							<ul class="brochures-lists">
								<li class="active">
				<a href="{{URL::asset("/downloads/$data->path")}}" target="_blank">
										<span>{{$data->extension}}</span>{{$data->title}}<i class="fa fa-download"></i>
									</a>
								</li>
							</ul>
						</div>
						@endforeach
					</div>
				</div>



			</div>
		</div>
	</section>


@endsection